Ignore coveralls upload failures
I am once again seeing

    Submitting coverage to coveralls.io...
    Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
    resubmitting with id None
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 290, in submit_report
        response.raise_for_status()
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/cli.py", line 95, in main
        result = coverallz.wear()
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 257, in wear
        return self.submit_report(json_string)
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 293, in submit_report
        raise CoverallsException(
    coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobsSubmitting coverage to coveralls.io...
    Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
    resubmitting with id None
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 290, in submit_report
        response.raise_for_status()
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/cli.py", line 95, in main
        result = coverallz.wear()
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 257, in wear
        return self.submit_report(json_string)
      File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 293, in submit_report
        raise CoverallsException(
    coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

when nothing has changed in my repo or configuration.

I've had enough of coveralls.  If the numbers fail to upload, so be it.