Revert "Why not go for broke?  Let's try breezy"
This reverts commit 0ccbcdaa86dd93dd2f4b17b24d909dcfb51b2764.

Nah, the brz package is broken in 24.04.

    + bzr --version
    brz: ERROR: Couldn't import breezy and dependencies.
    Please check the directory containing breezy is on your PYTHONPATH.

    Error: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'breezy'"), traceback: None }