Fixed a bug in error reporting
The error in question:

  TypeError: descriptor '__init__' requires a 'exceptions.Exception' object but received a 'str'